### ISSUE TITLE
DHA2: GISC Roles, Permissions, SEC Policy

### ISSUE THREAD

**Issue by openwis-ss** [OpenWIS/openwis#126]
Capture GISC Roles and Permissions and Security Policy

Identify the various roles and permiss used in OpenWIS

(eg.)
Role: Metadata Administrator
Function: Edit Metadata, Delete Metadata

**Comment by lmika-bom** [comment]
I think this can be considered done.

**Comment by rogers492** [comment]
Ok, closed.
