### ISSUE TITLE
Flash plugin notification in Portal

### ISSUE THREAD

**Issue by openwis-ss** [OpenWIS/openwis#135]
open the user portal in FireFox I get the message “Firefox has prevented the outdataed plugin “Adobe Flash” from running on wis.metoffice,gov.uk”

Should the portal be using a flash plugin ?

**Comment by lmika-bom** [comment]
Low impact issue which comes from using ExtJS, that has been superseeded by Angular.

**Comment by rogers492** [comment]
ok, closed.
