### ISSUE TITLE
Maven 3 build failure

### ISSUE THREAD

**Issue by ShaunDAdams** [OpenWIS/openwis#136]
OpenWIS fails to compile when using Maven 3 (3.1.1)

[ERROR] Failed to execute goal org.apache.cxf:cxf-java2ws-plugin:2.1.10:java2ws (cacheindex-service-wsdl) on project openwis-dataservice-cache-ejb: org/openwis/dataservice/cache/CacheIndex: org.openwis.dataservice.cache.CacheIndex -> [Help 1]

This is the only module that fails to build in Maven 3

**Comment by rogers492** [comment]
OpenWIS is now using maven 3 for current builds.
