### ISSUE TITLE
Add vagrant to repository using Puppet for provisioning

### ISSUE THREAD

**Issue by lmika-bom** [OpenWIS/openwis#169]
Move the vagrant files into the OpenWIS repository and modify them to work with the sanitised Puppet scripts UKMO is working on.  Use appropriate configuration so as to make it easy for developers to spin up and start using an instance of OpenWIS.

**Comment by lmika-bom** [comment]
We've got a working Vagrant for 3.0 so may not be worth investing too much into the purity of the solution.

**Comment by rogers492** [comment]
ok, closed.
