### ISSUE TITLE
WCMP version 1.3: Use of gmx:Anchor for data policy

### ISSUE THREAD

**Issue by lmika-bom** [OpenWIS/openwis#172]
During TT-GISC-2016, it was mentioned that it is legal to use gmx:Anchor in place of gmx:CharacterString (or free-text) to represent the data policy (XPath `//gmd:resourceContraints/*/gmd:otherConstraints/`).  Initial findings suggest that OpenWIS currently does not support this.

Please investigate and fix if this is the case.

More information: 
- [TT-GISC2016-Doc06-DataPolicies.docx](http://wis.wmo.int/file=2541)
- Section 9.3.2 of WCMP 1.3 Specification (Part 1)

**Comment by lmika-bom** [comment]
Have been pushed by TT-GISC-2016 so should get this fixed if it's not doing this already.

**Comment by rogers492** [comment]
This issue was moved to OpenWIS/openwis4#74
