### ISSUE TITLE
Openam needs downgraded Java Version

### ISSUE THREAD

**Issue by mgiannoni** [OpenWIS/openwis#173]
For the Portals to be compatible with updated JDK-1.7, OpenAM must be upgraded to 12.0.0.    From examining the Forgerock release notes, there are changes in the OpenAM-Shared library API that will affect the Portals.

[openam-12.0.2-release-notes.pdf](https://github.com/OpenWIS/openwis/files/225941/openam-12.0.2-release-notes.pdf)

[openam-13-release-notes.pdf](https://github.com/OpenWIS/openwis/files/225944/openam-13-release-notes.pdf)

[OpenAM 12.0.0 Developers Guide](https://backstage.forgerock.com/static/docs/openam/12.0.0/dev-guide/pdf/openam-12.0.0-dev-guide.pdf)

[OpenAM 13.0.0 Developers Guide](https://backstage.forgerock.com/static/docs/openam/13/dev-guide/pdf/openam-13-dev-guide.pdf)

**Comment by rogers492** [comment]
Fixed in version 3.14.8
