### ISSUE TITLE
Binaries / Middleware and artefact folders confusion

### ISSUE THREAD

**Issue by gollogly** [OpenWIS/openwis#177]
There are a number of folders in the webdav repo in cloudbees which is causing some confusion.
- binaries - Holding the binaries for reference in installing the software. (This is also under the private repo and not it's own repository)
- artefacts - was unused but a more suitable location to hold release artifacts
- middleware temporary folder that only gets populated by use for the integration environment and can have different versions depending on which step of the uplift is being preformed. This is not always available and is volatile in nature

I recommend

Dropping binaries and create a release structure under artefacts repo instead. The release notes will need to be updated to reference this new structure
- artefacts
  - 3.12
  - 3.14.5

**Comment by rogers492** [comment]
Fixed in 3.14.7 open source package #212
