### ISSUE TITLE
Browse Cache Content - search broken (v3.14.5)

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis#189]
The search within 'Browse Cache Content' is broken on the Admin Portal on our DEV system
(where only Brazilia and Melbourne have been harvested and only Brazilian and Australian data is sent to the cache)
It does not dispaly the search results correctly. Only page 1 of the results does. - Not very helpful if what is being searched for is on page 2 or later.

to replicate:
on the Admin Portal > Data Service > Browse content page
enter SPAU65 in the 'Metadata ID' box and click search
Page 1 shows data with that metadata ID and a total at bottom eg  'page 1 of 3' and 'Displaying data 1-20 of 42'
but...
clicking the 'next page' arrow to go to page 2 brings up data that does not match the search and the total at the bottom changes to 'page 2 of 490' and 'Displaying data 21-40 of 9788'

**Comment by lmika-bom** [comment]
This has been fixed.  Can be closed.

**Comment by rogers492** [comment]
ok, closed.
