### ISSUE TITLE
Puppet and OpenWIS Config consolidation

### ISSUE THREAD

**Issue by gollogly** [OpenWIS/openwis#196]
Config files such as portal config.xml and various other application config/scripts now live under openwis and under the resource/puppets file directories. I suggest these are concolidated and removed from openwis files directories as they will easily get mismatched in future. 

I recommend if the puppet scripts are used to build environments that this issue is resolved within the OpenWIS code to decouple config and code when adopting puppet so that environment specific config can be set up easier.

Original issue raised as part of https://github.com/OpenWIS/openwis-deploy/issues/71

**Comment by lmika-bom** [comment]
Not sure what this is, but tied to a PR that was closed 7 months ago.  So marking it as "Close Me".

**Comment by rogers492** [comment]
ok, closed.
