### ISSUE TITLE
alarmmanagerservice wsdl url is invalid in portals

### ISSUE THREAD

**Issue by gollogly** [OpenWIS/openwis#199]
The current url doesn't resolve to a valid web service and throws an exception

It should be
openwis.management.useralarmmanager.wsdl=http://@dataServiceServer@/openwis-dataservice-server-ejb/UserAlarmManagerWebService/UserAlarmManagerWebService?wsdl

**Comment by lmika-bom** [comment]
Not clear where this miss-configuration occurs.  May affect data service default configuration, hence `v3-and-v4`.

**Comment by lmika-bom** [comment]
Actually, probably easier to just close this one.

**Comment by rogers492** [comment]
ok, closed.
