### ISSUE TITLE
question about how subscriptions are handled when metadata is removed

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis#211]
small question

I notice that there has been some activity with metadata in recent months around the GISCs... so
What happens when a user has subscribed to some harvested metadata that is later removed by the originating provider?
I don't seem to be able to remove metadata manually on OpenWIS when there are subscriptions attached. 
Won't this cause catalogue discrepancies between the GISCs?

**Comment by lmika-bom** [comment]
No real reason to fix this for v3, but might be worth thinking about for v4 as this is re-implemented.

**Comment by rogers492** [comment]
This issue was moved to OpenWIS/openwis4#56
