### ISSUE TITLE
Blacklisting - setting thresholds - be aware

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis#213]
I notice that when using just the default thresholds:

Nb Warn = 50
Nb Blacklist = 100

when the Nb Warn limit is reached an email is sent warning the user they have reached a threshold... But for every file sent after that point until the final email that blacklists the account they receive another warning email for every single file sent.
in this case the user receives 50 warning emails plus 1 more email that announces that they have been blacklisted for going over the blacklist threshold of 100

I discovered this as I had been testing blacklisting to see if it helped with the delivery failure/email storm issue and I received 51 emails within the space of 12 minutes. So this creates another email spamming issue. It was only a single subscription as well! Dread to think how quickly this would happen in reality with other subscriptions set up.

surely one or two emails would be enough notice.

Also, I don't really see the point of these thresholds since users should be able to have subscriptions to potentailly all the data in the cache (depending on privileges), but if they are required then I would assume that in reality these thresholds would need to be set substantially higher. The Cache at the moment is around 500,000 files, if the thresholds are say set at Nb Warn 400,000 Nb Blacklist 600,000 that would lead to a receipt of 200,000 emails warning of the number of files disseminated. Ouch! 
Hence why I question this feature.

I suppose we need to work out why we need these thresholds and how to use them? or disable them?

It seems that OpenWIS loves to spam emails to users. It is not a good characteristic and needs to be addressed asap.

**Comment by rogers492** [comment]
This issue was moved to OpenWIS/openwis4#75
