### ISSUE TITLE
need a way to update subscription delivery addresses for multiple subscriptions for a user in bulk

### ISSUE THREAD

**Issue by woollattd** [OpenWIS/openwis#237]
I have taken a look on the User Portal and don't see a method for a user to update destination address for multiple subscriptions, other than opening each subscription and modifying the destination manually.
This is very non user friendly since it is possible (expected) to have scores of subscriptions.
Hopefully we can make sure this is possible in OpenWIS v4.x

**Comment by lmika-bom** [comment]
Not sure it's worth perusing this feature in OpenWIS 3.0

**Comment by rogers492** [comment]
This issue was moved to OpenWIS/openwis4#58
