### ISSUE TITLE
MonitoringRequestWindow : Improve of request/subscriptions windows

### ISSUE THREAD

**Issue by jpjanecek-mto** [OpenWIS/openwis#241]
In the admin portal the user's process id is not present in the current query monitoring table (Data service > Monitor current requests > Current requests). A field "process id" could be added.

**Comment by lmika-bom** [comment]
Check in OpenWIS 4 as that UI would probably be modelled from OpenWIS 3.0.

**Comment by rogers492** [comment]
This issue was moved to OpenWIS/openwis4#76

**Comment by rogers492** [comment]
This issue was moved to OpenWIS/openwis4#77
