### ISSUE TITLE
Solr index mishandling

### ISSUE THREAD

**Issue by jpjanecek-mto** [OpenWIS/openwis#242]
UpdateIndex bug : the record of SpatialIndex table is in fact an append.
Solr bug : duplicated request index at metadata creation.

**Comment by lmika-bom** [comment]
Set milestone to `v3` only as index handling may be quite different in GN 3 (OpenWIS 4).

**Comment by benjaminsaclier** [comment]
Bug has been corrected in version 3.14 (push by MF)
