### ISSUE TITLE
Confusion of README files on GitHub

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis#250]
We have 2 different README files on GitHub - which one you see depends on which branch you open (try master vs develop).  Is this deliberate?  It seems confusing to me and makes keeping project info up to date a little complex.  

Release 3.14.7.1 currently has the develop style README, but was created as the preferred operational branch, so I assume it needs to direct people to Dimitris' installation guide.

@lmika-bom what do you think?

**Comment by lmika-bom** [comment]
Probably the one in develop, as that was the one updated as part of the OSS release.

**Comment by lmika-bom** [comment]
This affects version 3 but it might be necessary to revised the Readme for OpenWIS 4 a little.

**Comment by rogers492** [comment]
I have updated the README for v4 (https://github.com/OpenWIS/openwis4/blob/develop/README.md) to include preamble on WIS and license info.  V3 also has the license info etc, so closing this.
