### ISSUE TITLE
Closed ForgeRock Repo ?

### ISSUE THREAD

**Issue by mgiannoni** [OpenWIS/openwis#254]
Unable to resolve ForgeRock dependencides.  Should I be using a local build of the ForgeRock components? 

Failed to read artifact descriptor for org.forgerock.openam:openam-idpdiscovery:jar:12.0.0: 
Could not transfer artifact org.forgerock.openam:openam-idpdiscovery:pom:12.0.0 from/to forgerock-staging-repo (http://maven.forgerock.org/repo/releases):  Not authorized , ReasonPhrase:Unauthorized.

**Comment by rogers492** [comment]
Hi Marc, is this the same issue we just discussed on the scrum call?  What are you trying to build?  The guys from ED are just finishing the 3.14.8 build which includes the resolution of the closed ForgeRock repo.  That activity is part of this ticket: https://github.com/OpenWIS/openwis-documentation/issues/182

**Comment by mgiannoni** [comment]
Paul

Yes.  When I heard about the issue, I attempted a fresh 3.14.8 build and
verified the problem.
Forgerock apparently has outsourced their repo
<http://maven.forgerock.org/repo/webapp/#/home> .  I was not able to access
the URL from the Maven Build without a password.
My Forgerock "backstage" account does not have enough privilege.

Cheers!

Marc Giannoni
Unix System Engineer
Phone: 301.427.9478
Cell: 301.915.5266

**Comment by rogers492** [comment]
Ok. The ED guys will be putting the ForgeRock artefacts onto their server and pointing maven at that.  When they're done you are free to do the same.

**Comment by rogers492** [comment]
Hi @dimipapadeas Please let @mgiannoni know when you have the ForgeRock artefacts ready.
cheers!

**Comment by dimipapadeas** [comment]
@mgiannoni we have submitted a Pull Request [255](https://github.com/OpenWIS/openwis/pull/255), I will let you as soon as it is merged.

**Comment by mgiannoni** [comment]
Works!  Thanks for the fix...
