### ISSUE TITLE
Upgrading Security Service to use OpenAM 3.x and OpenDJ 3.x

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis#272]
_From @mgiannoni on August 14, 2017 18:23_

Update ForgeRock common libraries from 12.0.0 to 13.0.0:
1. openwis/pom.xml
Multiple changes in ForgeRock API javascript:
2. openwis-metadataportal/openwis-portal/src/main/webapp/saml2/jsp/

_Copied from original issue: OpenWIS/openwis-documentation#308_

**Comment by mgiannoni** [comment]
Successful Federation Authentication trial with OpenAM 13.0.0 with OpenDJ 3.0.0 with the new OpenAM 13.0.0 common libraries in the GeoNetwork portal code!  Request for a branch named "Platform Support" so we can post our changes.

**Comment by mgiannoni** [comment]
Pull Request [https://github.com/OpenWIS/openwis/pull/276](url)
