### ISSUE TITLE
Jboss WildFly 8.2.x OpenWIS DataService Support

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis#274]
_From @mgiannoni on August 14, 2017 17:42_

1. change the application.xml in openwis-dataservice.ear:  <initialize-in-order>true</initialize-in-order> to  <initialize-in-order>false</initialize-in-order>.

2. change six enterprise beans' jndi lookup strings to use java:app namespace instead of ejb: namespace: DisseminationManagerTimerService, DisseminationStatusMonitor, PackedFeedingTimerService, SplittingTimerService, CacheIndex, and CacheManager.

3. change the dependency scope to "provided" in for "<groupId>io.openwis.dataservice.cache</groupId>  <artifactId>openwis-dataservice-cache-core</artifactId>    <version>${project.version}</version>" in the POM file:  openwis-dataservice/openwis-dataservice-cache/openwis-dataservice-cache-webapp/pom.xml

4. change an enterprise bean ExtractionTimerService from local view to remote: 
openwis-dataservice/openwis-dataservice-server/openwis-dataservice-server-ejb/src/main/java/org/openwis/datasource/server/service/impl/ExtractionTimerServiceImpl.java

_Copied from original issue: OpenWIS/openwis-documentation#306_

**Comment by mgiannoni** [comment]
Successful DataService ManagementService deployment with Java-8 and Wildfly 8! Request for a branch named "Platform Support" so we can post our changes.

**Comment by mgiannoni** [comment]
Pull Request: [https://github.com/OpenWIS/openwis/pull/276](url)

**Comment by zhangz555** [comment]
Those changes reflected our efforts at MDL to modify the JNDI related configurations so that EJBs can work properly.
