### ISSUE TITLE
Initialise centre in LDAP

### ISSUE THREAD

**Issue by ussof** [OpenWIS/openwis#275]
Hello everybody !
I've been following the deployment instructions of the 3.14.5 version of openwis (https://github.com/OpenWIS/openwis/wiki/v3.14.5.1-Deployment-Instructions) and i'm stuck in the 3.5 section of the installation that explains how to initialise the LDAP centre. this is what i get each time i try to initialise a centre :
************************************************************
------ Populate LDAP ------ 
[1] Initialize Deployment
[2] Populate LDAP
[3] Reset LDAP Users
[4] Reset LDAP Groups
[5] Reset LDAP Users And Groups
Choose one of the above values. (any other value to exit)
1
Initialize Deployment:
Deployment Name:
openwis
Administrator Login:
openwis
Administrator Password:
open
Administrator Email:
open@mail.ma
Administrator First name:
openwis
Administrator Last name:
openwis
org.openwis.securityservice.UserManagementException_Exception: Fault occurred while processing.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:136)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:135)
	at com.sun.proxy.$Proxy23.initialize(Unknown Source)
	at org.openwis.usermanagement.PopulateUser.initializeDeployment(PopulateUser.java:158)
	at org.openwis.usermanagement.PopulateUser.displayMenu(PopulateUser.java:46)
	at org.openwis.usermanagement.PopulateUser.main(PopulateUser.java:239)
************************************************************
I have checked the management service URLs of both user and group in the "populate.sh" script and they seem to be correct (the management services are deployed in tomcat) : 
userManagementServiceWsdl=http://localhost:8080/openwis-securityservice/services/UserManagementService?wsdl
groupManagementServiceWsdl=http://localhost:8080/openwis-securityservice/services/GroupManagementService?wsdl
I'm using the jar : openwis-securityservice-utils-populate-ldap-3.14.5.jar
When i checked the master branch of the project, i found that @mgiannoni is mentioning something about the web services that previously were deployed on jboss and weren't updated in the java files of the current version :  openwis/openwis-securityservice/openwis-securityservice-utils/PopulateLDAP/src/main/java/org/openwis/usermanagement/ServiceProvider.java 

I was considering to edit and compile the ServiceProvider.java file but It wasn't as easy as i taught it would be. I'm wondering if there is a way for me to get around this issue ?

Thanks in advance !

**Comment by dimipapadeas** [comment]
Hi @ussof , 
please verify that you are using the proper version of JDK  as described at [2.4.1 JAVA RPM install](https://github.com/OpenWIS/openwis/wiki/v3.14.5.1-Deployment-Instructions#241java-rpm-install)

 Also check  the configured values in the file populateLDAP.sh of **CLASSPATH** and **java -classpath** to be  likewise the following example:

![image](https://user-images.githubusercontent.com/20535822/31545715-372ffba8-b029-11e7-9af5-1c7c7a9a6e3a.png)

Please let me know if it worked

**Comment by ussof** [comment]
Hi @dimipapadeas,
Thanks for the quick reply 
this is the content of populateLDAP.sh : 
***************************************************
RACINE=.
LIB=$RACINE/lib

for jarFile in $LIB/*.jar; do
	APP_LIB="$APP_LIB:$jarFile"
done

CLASSPATH="$APP_LIB:openwis-securityservice-utils-populate-ldap-3.14.5.jar"

userManagementServiceWsdl=http://localhost:8080/openwis-securityservice/services/UserManagementService?wsdl
groupManagementServiceWsdl=http://localhost:8080/openwis-securityservice/services/GroupManagementService?wsdl

java -classpath $CLASSPATH -DuserManagementServiceWsdl=$userManagementServiceWsdl -DgroupManagementServiceWsdl=$groupManagementServiceWsdl org.openwis.usermanagement.PopulateUser 
***************************************************
I see that you've added "/home/openwis/openwis/openwis-portal-client/target/classes" to the CLASSPATH variable.
as for java,i think that i'm using the correct version : 
echo $JAVA_HOME 
/usr/java/jdk1.7.0_65/jre 

i will try to update my CLASSPATH and see what i get, 
I will let you know as soon as i do it

**Comment by ussof** [comment]
Hi @dimipapadeas,
I can't find "/home/openwis/openwis/openwis-portal-client/target/classes" anywhere, but i found out that "/home/openwis/PopulateLDAP/lib/openwis-portal-client-3.14.5.jar" is already referenced in the lib directory of PopulateLDAP and it's taken into account by populateLDAP.sh (APP_LIB variable).
I tried extracting this jar file and including its classes in my CLASSPATH but i keep getting the same errors. If you think i'm using a wrong directory, could you please point out the correct one ?
Thanks again !

**Comment by dimipapadeas** [comment]
The path is where you must have already checkout  the OpenWIS v3, inside the openwis folder there must be an **openwis-portal-client** folder. If you have build it  [according to manual](https://github.com/OpenWIS/openwis/wiki/Getting-Started), there must be `/target/classes/ folders`, whose absolute path you need to point at your classpath.

**Comment by ussof** [comment]
It seems like i was missing that one, i rebuilt the project and now i have the folder, i relaunched the script with the same values as you did in the example, but unfortunately i keep getting the same errors. I think that a fresh installation might be my only way out of this because i can't figure out what i'm missing.

**Comment by dimipapadeas** [comment]
Please note that, this installation is a rather complex procedure and even a minor misconfiguration may lead to failure. You must be very careful when executing commands. I would suggest an extensive study of the document before starting the installation. 

Any feedback is welcome.

**Comment by ussof** [comment]
Thank you @dimipapadeas , i will do that.

**Comment by ussof** [comment]
Hello @dimipapadeas !
I'm droping you this comment just to let you know that i was able to run the script properly without problems. It seems like there was something wrong in my LDAP server configuration because the script worked after i reinstalled opendj & openam.
