### ISSUE TITLE
Java exception on request/subscribe click

### ISSUE THREAD

**Issue by teonar** [OpenWIS/openwis#291]
Openwis 3.14.5
Steps:
Do geographical search
Choose one of the results that shows up
Click on the Subscribe/Request button

An error occurred. Please contact your service desk.

And in the log files
ERROR [jeeves.service] - Raised exception while executing service
java.lang.NullPointerException at org.openwis.metadataportal.services.request.GetAllSubSelectionParameters.exec(GetAllSubSelectionParameters.java:67)

No idea why this is happening, any pointers ?

**Comment by woollattd** [comment]
sorry no idea. But it seems ok on our system (3.14.5)- not much help I know, but maybe indicates an installation/configuration problem? or maybe a metadata related issue?
The SubSelectionParameters is the first tab that is displayed when the window pops up once the Request or Subscribe buttons are clicked.
Does this happen for all metadata? I chose "IURD13 BUFR bulletin available from EUMG (EUMETSAT - DARMSTADT)" from the geopraphivcal search, does this one cause the problem for you?

**Comment by teonar** [comment]
Pretty sure it is a install/config issue but I am lost as to where to begin seaching, I will download the "IURD13 BUFR bulletin metadata and feed it to the system just to see if the metadata isnt the problem.

**Comment by solson-nws** [comment]
@teonar  - Is this still an issue with 3.14.10 or 3.15?

**Comment by davidpodeur** [comment]
Just reported by @yvesgoupil that this does not happen on MF GISC setup neither in 3.13, nor 3.14.10.
