### ISSUE TITLE
Disable SSL certificate verification in python (wismon)

### ISSUE THREAD

**Issue by JeyoungRyu** [OpenWIS/openwis#295]
When generating the “centres.json” file using wismon, if the urls of the target GISC (portal, oaipmh, sru) use https, there are the error that "SSL certificate verify fail" occurs and the response are not received.
KMA confirmed the log of the network response time with GISC Tokyo as "-1", and found the log as the attached image.

![jma](https://user-images.githubusercontent.com/24219454/43374240-34a451dc-939e-11e8-998a-b753c182ca1a.PNG)

The KMA could be resolved by adding the following two lines to the wismon source code (wismon.py):

import ssl
![wismon_im1](https://user-images.githubusercontent.com/24219454/43374278-48adc136-939e-11e8-81ad-66af7031ac45.png)

ssl._create_default_https_context = ssl._create_unverified_context
![wismon_im2](https://user-images.githubusercontent.com/24219454/43374284-5075fdd4-939e-11e8-9f61-e2e7a7fa33ab.png)

**Comment by SungsooDO** [comment]
Thank you for your email. I will be out of the office until Wednesday 1st August, so I'll respond to your message as soon as possible when I return. 




             #signDiv {background-color: #ffffff;}            #signDiv BODY{ background-color: #ffffff;}            #signDiv BODY, #signDiv TD, #signDiv TH { color: black; font-family: 굴림; font-size: 12px; }            #signDiv TD { border: 0px}             #signDiv P { margin: 0px; padding:0px}        ====== Watching the Sky Friendly, Serving the People Faithfully ======
DO, Sungsoo ( 都 性 秀 )
Information & Communication Technology Division
Korea Meteorological Administration
 
Tel : +82-2-2181-0424
Cel : +82-10-2855-3357
E-mail : ssdo@kma.go.kr
61 Yeoeuidaebang-ro 16-gil Dongjak-guSeoul, Republic of KOREA
====================================================================

**Comment by solson-nws** [comment]
@JeyoungRyu -- Did you ever create a pull request to introduce this fix for the wismon portion of OpenWIS?  What's unclear is whether or not your fix was implemented in the revised WISMON codes with the last update?  Can you please clarify?

Steve
