### ISSUE TITLE
Adding licence aggreementon user portal registration

### ISSUE THREAD

**Issue by benjaminsaclier** [OpenWIS/openwis#297]
It would be useful to have the possibility to force a user to accept a licence during registration.
We (Meteo-France) propose to implement this functionality which will be optional ( an administration parameter will allow to display or not the licence in the registration portal).
 
![screenshot-maccp-raq-int meteo fr-2018 09 17-10-18-48](https://user-images.githubusercontent.com/12250260/45612378-187a5880-ba63-11e8-986c-b308b1aafd20.png)

**Comment by solson-nws** [comment]
This is no longer required. Closing this ticket
