### ISSUE TITLE
Write functional requirements for authentication and authorization (Keycloak) 

### ISSUE THREAD

**Issue by benjaminsaclier** [OpenWIS/openwis#322]
Write the requirements to replace OpenAM/OpenDJ by another identity server.

**Comment by solson-nws** [comment]
@benjaminsaclier  @yvesgoupil  @mgiannoni  @zhangz555 :  Let me get this started

**Goals:** 

- To maintain open-source nature associated with the security service.  With Forgerock closign repo, we need to eliminate the need for reliance on community version of OpenAM/OpenDJ

- Make the security service installation more user friendly and easier.  Current process is cumbersome

- Continue to support SAML

**Objectives:**

- Consider alternatives to the OpenAM/OpenDJ security service solution that doesn't eliminate features currently in use by existing OpenWIS versions

- Re-align security service with a well established and supported open source community

- Consider WIS 2 aspects involving security when examining alternatives for security service 

**What's important in an alternative:**

- Ease of use

- patchability

- community support

- Integration with existing code base

- No loss of functionality

**Key dependencies to overcome:**

- Zhan, can you do an analysis on this?

**Comment by solson-nws** [comment]
This ticket can be closed.  A decision was made to stick wtih OpenAM middleware, just integrating the OpenAM API and removing the dependencies in OpenWIS code.
