### ISSUE TITLE
openwis-dataservice.properties file update required

### ISSUE THREAD

**Issue by yvesgoupil** [OpenWIS/openwis#326]
EJB JNDI names:
 'ejb:' should be replaced by 'java:global/' in the properties file
`~/openwis/openwis-dataservice/openwis-dataservice-config/src/main/config/openwis-dataservice.properties"`

**Comment by solson-nws** [comment]
@yvesgoupil :  Has this been checked in as a pull request?

@zhangz555 and @mgiannoni :  Do you agree with Yves suggested change?

**Comment by mgiannoni** [comment]
Yes this is the correct update.  It's an artifact from the branch used by 3.15 predating the Java 7 update submitted by NWS

**Comment by solson-nws** [comment]
@yvesgoupil, can you please confirmed that this is in the OpenWIS 3.15 branch.  And if it is, please close the ticket.

**Comment by solson-nws** [comment]
This ticket can be closed.  It was fixed in the 3.15 version.
