### ISSUE TITLE
Travis CI build failure on Merging pull request #328 from OpenWIS/openwis-3.14.10

### ISSUE THREAD

**Issue by zhangz555** [OpenWIS/openwis#334]
Travis CI build failure on Merging pull request #328 from OpenWIS/openwis-3.14.10. 
Please see https://travis-ci.org/github/OpenWIS/openwis

**Comment by zhangz555** [comment]
The build log reveals that the failure occurs at the deployment related script. 
![image](https://user-images.githubusercontent.com/9867607/85468887-02c08e00-b57b-11ea-9ce4-995c077f5faf.png)

**Comment by zhangz555** [comment]
A new branch travis-build-issue is created. New fix is added. Travis build is successful. See here https://travis-ci.org/github/OpenWIS/openwis/builds, #160

**Comment by zhangz555** [comment]
A new pull request is created.https://github.com/OpenWIS/openwis/pull/338

**Comment by solson-nws** [comment]
Closing Issue.  This is resolved and merged into master
