### ISSUE TITLE
Investigation on an OpenWIS Security Component Alternative: the Approach of Utilizing Keycloak Valve Infrastructure and Keycloak Java API Library

### ISSUE THREAD

**Issue by zhangz555** [OpenWIS/openwis#342]
Our investigation of Keycloak focuses on critical security features that already exists in OpenWIS. Our goal is to implement those features by utilizing Keycloak provisions. We pay special attention to these areas: SAML authentication, sign-in/sign-off workflow, SSO, management of users, groups, and data policies.

**Comment by zhangz555** [comment]
Example web applications that utilize Keycloak Valve Infrastructure and Keycloak Java API library are written. These example apps demonstrate critical features existing inside the current OpenWIS security components such as portals, and OpenAM/DJ. The entire effort is to prove that Keycloak domain can provide a viable alternative to the current OpenWIS security component.

**Comment by zhangz555** [comment]
A combination of Keycloak valve infrastructure, Keycloak Java APIs, and Keycloak Restful APIs are utilized in the design. This should be similar to the integration approach adopted in OpenWIS portals. The design similarity should enhance the viability of this Keycloak approach in the aspect of security component integration into the OpenWIS system.

An IdP managed data model is adopted. This can be changed into a Idp and clients co-management model. For instance, some data can be stored in a client managed database. Note that currently this blend data model is adopted in the OpenWIS system.

Roles in web.xml is removed, and complete code controlled, role based, dynamic content access is implement in the design. This should reduce code change efforts in the OpenWIS portals integration should the investigated Keycloak approach be taken by the committee.

**Comment by zhangz555** [comment]
Investigation At a Glance:
- SAML authentication
- Workflow of sign in, doing something, then sign off
- User’s rolls listing
- User Attributes query
- User creation
- Group creation 
- Get rid of roles in web.xml, allowing complete-code-controlled, role-based, dynamic content access
- Data policy
- Single Sign-on (SSO), and issues in single log-off

**Comment by zhangz555** [comment]
Conclusion:
- Thorough investigation on Keycloak valve infrastructure and Keycloak Java API library is performed. The investigation focuses on critical security features that exists in OpenWIS. 
- Example web applications that utilize Keycloak provisions are written, so as to demonstrate critical features existing inside the current OpenWIS portals. 
- In the example web applications, design model, data model, and role based content access are handled in a similar approach as are in OpenWIS portals. This demonstrates the possibility of reduced code change efforts in OpenWIS portals integration, should the investigated Keycloak approach be taken by the committee.  
- Based on the process and findings in the investigation, we believe that the approach of utilizing Keycloak provisions would be a solid candidate in the effort of replacing current OpenWIS security components.

**Comment by zhangz555** [comment]
Advantages of Keycloak over OpenAM/DJ

Managed under Redhat as an open source product, Keycloak should generally provide better services over Forgerock’s OpenAM/DJ in the following areas:
- Openness and maintenance of open source code repositories. We had encountered partial closure of ForgeRock community repositories. 
- Patchability of API library code in case of middleware upgrades.   
- Technical support and community forums.

**Comment by zhangz555** [comment]
[To SC Keycloak Valve + API Approach final version.pdf](https://github.com/OpenWIS/openwis/files/5482237/To.SC.Keycloak.Valve.%2B.API.Approach.final.version.pdf)

**Comment by zhangz555** [comment]
Comments are highly welcome!

**Comment by zhangz555** [comment]
As I have told in the collaboration meeting, just a reminder that due to my tight time schedule, there are two functions that are not implemented yet, but I am sure that they can be done by utilizing the techniques we have already used in the design of the example web applications. Those two functions are: (1) when adding a user, associate him with a group; (2) add attributes to a group when creating data policies.

**Comment by solson-nws** [comment]
Closing this issue out. The keycloak investigate is complete.
