### ISSUE TITLE
Adding the jsp file "spGetToken.jsp" to OpenWIS 3.14.10 release

### ISSUE THREAD

**Issue by yvesgoupil** [OpenWIS/openwis#343]
The jsp file "spGetToken.jsp" is not included in OpenAM-13.0.0.war. This file must be available in OpenWIS 3.14.10 release. We have to decide where this file could be added. In openwis-dependencies.zip?

**Comment by mgiannoni** [comment]
Attached!

Marc Giannoni
Unix System Engineer, AceInfo Solutions
Phone: 301.427.9478
Cell: 301.915.5266

**Comment by yvesgoupil** [comment]
This file is described int the 3.14.10 Deployment Instructions wiki.
We leave it as it is.

**Comment by yvesgoupil** [comment]
We decide to close it on March 22, 2021.
