### ISSUE TITLE
Openwis v3.14.10 login error: Missing com.sun.identity.security.cert.CRLValidator in user and admin portal tomcat lib directory

### ISSUE THREAD

**Issue by yvesgoupil** [OpenWIS/openwis#348]
**Temporary workaround :**  

For both user and admin portals :  

`cp openam-shared-12.0.0.jar ~/apache-tomcat-9.0.24/webapps/openwis-user-portal/WEB-INF/lib/ `

(and do not remove openam-shared-13.0.0.jar !)

Stop/start openwis user or admin portal

Login test: login is ok and there is no error in catalina.out log anymore :

...
24-Sep-2020 15:28:38.972 INFOS [http-nio-8080-exec-8] com.sun.identity.plugin.log.impl.FedletLogger.access REDIRECT_TO_IDP
{http://gisc-int.meteo.fr:80/openam/SSORedirect/metaAlias/idp}  
24-Sep-2020 15:28:44.885 INFOS [http-nio-8080-exec-10] com.sun.identity.plugin.log.impl.FedletLogger.access GOT_RESPONSE_FROM_POST
{}  
24-Sep-2020 15:28:44.900 INFOS [http-nio-8080-exec-10] com.sun.identity.plugin.log.impl.FedletLogger.access FOUND_AUTHN_ASSERTION
{s273f5ef967ab730d6944de1ba5a7b7a23251c62b1}
{}
{s240a03d1f1a5fb37b5bd7f1ccb7269faa362f0b01}  
24-Sep-2020 15:28:44.901 INFOS [http-nio-8080-exec-10] com.sun.identity.plugin.log.impl.FedletLogger.access SUCCESS_FED_SSO
{anonymous}
{XSto4EgP+W//AjZ17CHmzbIwQPqi}
{anonymous}
...

**Comment by solson-nws** [comment]
This ticket will be closed.  It's become part of the revised middleware and will be fixed with the next version.
