### ISSUE TITLE
Maintenance Risks Analysis on  Dependency Components in OpenWIS 3.15

### ISSUE THREAD

**Issue by zhangz555** [OpenWIS/openwis#365]
There are various software systems and other third-party components that are dependencies of OpenWIS version 3.15. Detailed information on OpenWIS 3.15 installation  can be referred to at location https://github.com/OpenWIS/openwis/wiki/v3.15.0-Deployment-Instructions. In the lifetime of this OpenWIS version, updating software dependency components will be needed in regular maintenance efforts due to legitimate reasons. Ties to these dependencies in OpenWIS code sets normally require code modification and testing after updating. We will list out update options for these dependency components, and analyze risks involved in each update, including impacts to the system, and complexity of the update itself. We also provided to the committee suggested precedences for updating. 

Currently, the version 3.15 is still in the test phase, and we have found several issues which are summarized here https://github.com/OpenWIS/openwis/issues/353.

**Comment by zhangz555** [comment]
The analysis document is attached here. 
[Maintenance Risks Analysis on Dependency Components in OpenWIS 3.15.pdf](https://github.com/OpenWIS/openwis/files/6454883/Maintenance.Risks.Analysis.on.Dependency.Components.in.OpenWIS.3.15.pdf)

**Comment by solson-nws** [comment]
This issue can be closed for OpenWIS 3.15.  This applied to 2021 analysis
