### ISSUE TITLE
Openwis v3.14.10 - user is not deleted in ldap group

### ISSUE THREAD

**Issue by yvesgoupil** [OpenWIS/openwis#386]
When a user is deleted in admin portal, the user is not deleted in ldap group.

**Comment by yvesgoupil** [comment]
Fixed by Hacene from Akka in "openwis-3.14.10_issue_386" branch.
Commit: https://github.com/OpenWIS/openwis/commit/ac413a1dd0b8f8996f3ad863f39b853613a06ff2 .

**Comment by yvesgoupil** [comment]
"openwis-3.14.10_issue_386" branch should be merged in master.

**Comment by solson-nws** [comment]
@yvesgoupil - Did you create a pull request to merge this into master?

**Comment by solson-nws** [comment]
Closing this issue based on @yvesgoupil suggestion.
