### ISSUE TITLE
Map not showing

### ISSUE THREAD

**Issue by ywang-bom** [OpenWIS/openwis#75]
All the maps are not showing up. This includes the maps for search, the map in web metadata editor and the maps in sub-selection parameter (for BoM LocalDataSource). 

Since the map is loaded from an exteranal map server. It disappears when the remote server goes down or changes service. This is mostly likely the same issue that DCPC FMI has encountered.

We may want to look into this issue and have an usable mapserver as part of the default configurations.

**Comment by lmika-bom** [comment]
Not sure if this is still an issue.  It's been opened for a year and a half so I suggest closing it.  If it happens again, we could raise a new ticket.

**Comment by rogers492** [comment]
Ok, closed.
